error_reporting=E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED
date.timezone=UTC
memory_limit=512M

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=256
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=20000
opcache.validate_timestamps=0

[pcov]
pcov.enabled=1
pcov.directory=/app
pcov.exclude="~^/app/(?!src/)~"
